- Production|Industry|{Industry-Sector}:
    description: Production of industrial commodities by sector
    unit: Mt/yr

- Production|Industry|Iron and Steel|{Iron Commodity}:
    description: Production of steel commodities
    unit: Mt/yr
- Production|Industry|Non-metallic minerals|{Non-Metallic Minerals Commodity}:
    description: Production of mineralic commodities
    unit: Mt/yr
- Production|Industry|Non-ferrous metals|{Non-Ferrous Metals Commodity}:
    description: Production of non ferrous metals
    unit: Mt/yr
- Production|Industry|Chemicals|{Chemicals Commodity}:
    description: Production of chemical commodities
    unit: Mt/yr
- Production|Industry|Pulp and Paper|{Pulp and Paper Commodity}:
    description: Production of paper commodities
    unit: Mt/yr
